<template>
<div class="section-heading"><div><h1>我的猫咪</h1><p>查看猫咪信息，更新年龄和体重。</p></div><el-button type="primary" @click="$router.push('/buyer-show-recommend')">查看专属推荐<el-icon><IconArrowRight /></el-icon></el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false" class="form-alert" /><div class="cat-profile-grid" v-loading="loading"><section class="surface" v-for="cat in cats" :key="cat.catid"><div class="cat-profile-head"><img src="@/assets/img/catbackground.png" alt="猫咪档案头像" /><div><h2>{{ cat.catname }}</h2><span class="muted">{{ cat.description }}</span></div></div><el-descriptions :column="2"><el-descriptions-item label="品种">{{ cat.catkind }}</el-descriptions-item><el-descriptions-item label="年龄">{{ cat.catage }} 岁</el-descriptions-item><el-descriptions-item label="体重">{{ cat.catweight }} kg</el-descriptions-item><el-descriptions-item label="档案编号">#{{ cat.catid }}</el-descriptions-item></el-descriptions><el-button plain type="primary" @click="edit(cat)"><el-icon><IconEdit /></el-icon>更新成长信息</el-button></section></div><el-empty v-if="!loading && !cats.length" description="还没有猫咪档案" />
<el-dialog v-model="dialog" title="更新猫咪信息" width="420px" align-center><el-form label-position="top"><el-form-item label="年龄（岁）"><el-input-number v-model="form.catage" :min="0" :precision="0" /></el-form-item><el-form-item label="体重（kg）"><el-input-number v-model="form.catweight" :min="0.1" :precision="1" :step="0.1" /></el-form-item><el-form-item label="生长状态"><el-select v-model="form.catstate"><el-option v-for="option in states" :key="option.value" :label="option.label" :value="option.value" /></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</template>
<script>
import axios from 'axios';
import { ElMessage } from 'element-plus';
export default { data: () => ({cats:[],loading:false,error:'',dialog:false,form:{},states:[{value:1,label:'肥胖（计划减重）'},{value:2,label:'不活跃'},{value:3,label:'已绝育成年猫'},{value:4,label:'未绝育成年猫'},{value:5,label:'妊娠期'},{value:6,label:'哺乳期'},{value:7,label:'未成年'}]}),created() { this.load(); },methods:{
 async load() { this.loading=true; try { const user=(await axios.get('/now-usr')).data; if(!user) { this.error='登录后即可查看猫咪档案'; return; } const {data}=await axios.get('/cat/show-cat',{params:{ownerid:user.userid}}); this.cats=data.data || []; } catch { this.error='猫咪档案加载失败'; } finally {this.loading=false;} },
 edit(cat) {this.form={id:cat.catid,catage:cat.catage,catweight:cat.catweight,catstate:cat.catstate};this.dialog=true;},
 async save() {try {const {data}=await axios.post('/cat/modify-cat',null,{params:this.form});if(data.page==='error') throw new Error(data.msg);this.dialog=false;await this.load();ElMessage.success('成长信息已更新');}catch {ElMessage.error('保存失败，请重试');}},
} };
</script>
